### ISSUE TITLE
Dealing with titles that are too long for a slug field 

### ISSUE THREAD

**Issue by ivanvenosdel** [WimpyAnalytics/django-andablog#35]
Came across this issue in one of the forks. https://github.com/fedejaure/django-andablog/commit/1ece7f427f2bf215e67a1ed23fd81b7783b02238

A similar approach but something that makes the parts used a bit more dynamic (rather than always the first 4) could work. Tests for this would best be placed in [andablog's test_models](https://github.com/WimpyAnalytics/django-andablog/blob/master/andablog/tests/test_models.py).

**Comment by bradmontgomery** [comment]
I've run into this too. I'd be happy to submit a PR if you'll let me know what sort of slug-ification scheme you'd like to see. Here are some ideas:

*Idea 1*. Just keep the first 50 chars:

```python
>>> title = "Hi, I'm just your average every day title that's too long for it's own good"
>>> slugify(title)[:50]
'hi-im-just-your-average-every-day-title-thats-too-'
```

*Idea 2*. Prefix (or postfix) the slug with the Entry's id. This'll prevent issues if you had similar titles whose slugs collide. I've done this in other projects, but it takes two queries to save an Entry initially.

```python
>>> entry_id = str(entry.id)
>>> "-".join([entry_id, slugify(title)[:49 - len(entry_id)]])
'123-hi-im-just-your-average-every-day-title-thats-'
```

*Idea 3*. Similar to *idea 2*, we could generate a uuid or (a any hash) and use a short slice of it as a prefix or postfix for the slug.

```python
>>> from uuid import uuid4
>>> '-'.join([slugify(title)[:43], str(uuid4())[:6]])
'hi-im-just-your-average-every-day-title-tha-38a9bb'
```

Just a few ideas. Let me know what you think, and I'll send you a PR.

**Comment by bradmontgomery** [comment]
Other other thought. *Idea 2* has the added benefit that you can look up an entry by it's ID (without the rest of the slug) if you wanted to. This also means that changing a title might not break an old link to an entry. Perhaps that's Beyond the Scope, tho :)

**Comment by ivanvenosdel** [comment]
Great! Good point about idea 2. It's solution is actually a lot like the one mentioned in #27. Though I like the URL scheme there better.

With that said I think addressing #27 would be the best as it would address both issues. 

Otherwise, I would say idea 1 would be the best approach to just this one as it won't get in the way of implementing #27.

**Comment by ivanvenosdel** [comment]
The tests would land in the same spot regardless.
