### ISSUE TITLE
NoReverseMatch: Reverse for 'blog' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

### ISSUE THREAD

**Issue by janssja** [WimpyAnalytics/django-andablog#54]
Hi,
Might be an issue with me being a newbie on django.
I have the error mentioned in the subject with the following configuration:
navbar.html: `<li><a href="{% url 'andablog' %}">Blog</a></li>`
urls.py: `(r'^blog/', include('andablog.urls', namespace='andablog')),`
Can you help me?
Kind regards,
Jackie
PS.: blog is working when I use <website>/blog/

**Comment by ivanvenosdel** [comment]
Try this instead:
```html
<li><a href="{% url 'andablog:entrylist' %}">Blog</a></li>
```

If that works, where did you find the sample you were trying? We might have a bug in the docs.

**Comment by janssja** [comment]
That works. It's not in the bug in the docs. It was my own lack of knowledge. I did not know that you should use the : when using a namespace. Thanks a lot. Maybe it's a good idea to include the example somewhere in the docs.
Regards,
Jackie

**Comment by ivanvenosdel** [comment]
Docs updated, thanks for the feedback!
