### ISSUE TITLE
Django 2.0 compatibility

### ISSUE THREAD

**Issue by ivanvenosdel** [WimpyAnalytics/django-andablog#58]
Will discontinue support for 1.10.x

**Comment by ivanvenosdel** [comment]
Currently [blocked on the django-markitup project](https://github.com/zsiciarz/django-markitup/pull/21). Once we have a django2 compatible release for django-markitup we can continue development on the [django2 branch](https://github.com/WimpyAnalytics/django-andablog/tree/django2).

**Comment by KrunchMuffin** [comment]
So is this not going to get 2.1 update cause markitup doesn't seem to be doing it?

Any other simple blog out there with 2.1 support?

**Comment by ivanvenosdel** [comment]
I am in the middle of abandoning django-markitup and have put out a
candidate release for Django 2.0 compatibility.

After I am able to test that in a production project I will make it an
official release and work on 2.1 support shortly thereafter. This is top of
my list but my time is tight so hoping 1-4weeks for all of this work to get
done.

**Comment by ivanvenosdel** [comment]
3.0.0 has been officially released which is Django 2.0 compatible. Note that 3.0.0 **has not been tested with Django 2.1**. I am working on that next.

**Comment by ivanvenosdel** [comment]
@KrunchMuffin Just released 3.1.0, which covers Django 2.1 as well.
